/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.EventOrganizer;

import Model.Customer.Customer;
import Model.Database;
import Model.Event;
import Model.EventOrganizer;
import Model.Sponsor;
import Model.TicketManager.Ticket;
import Model.Venue;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Formatter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author evelynzu
 */
public class EventOrganizerPage extends javax.swing.JPanel {

    /**
     * Creates new form EventOrganizer
     */
    
    javax.swing.JPanel CardSequencePanel;
    EventOrganizer eventOrganizer;
    
    DefaultTableModel modelVenue;
    TableRowSorter tableRowSorterVenue;
    Venue selectedVenue;
    ArrayList<Venue> venues;
    
    DefaultTableModel modelS;
    TableRowSorter tableRowSorterS;
    Sponsor selectedSponsor;
    ArrayList<Sponsor> sponsors;
    
    DefaultTableModel modelE;
    TableRowSorter tableRowSorterE;
    Event selectedEvent;
    ArrayList<Event> events;
    
    Event newEvent;
    
    
    Database database;
    
    public EventOrganizerPage(JPanel clp, EventOrganizer eventOrganizer) {
        this.CardSequencePanel = clp;
        this.eventOrganizer = eventOrganizer;
        System.out.println(eventOrganizer.getUserAccount().getUser_id());
        initComponents();
        
        database = new Database();
        newEvent = new Event();
        
        venues = new ArrayList<>();
        dbGetVenue();
        populateVenueTable();
        tableRowSorterVenue = new TableRowSorter(modelVenue);
        tblVenue.setRowSorter(tableRowSorterVenue);
        
        sponsors = new ArrayList<>();
        dbGetSponsor();
        populateSponsorTable();
        tableRowSorterS = new TableRowSorter(modelS);
        tblSponsor.setRowSorter(tableRowSorterS);
        
        events = new ArrayList<>();
        dbGetEvent();
        populateEventTable();
        tableRowSorterE = new TableRowSorter(modelE);
        tblEvent.setRowSorter(tableRowSorterE);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfEventName = new javax.swing.JTextField();
        dateChooser = new com.toedter.calendar.JDateChooser();
        tfCustomerCapacity = new javax.swing.JTextField();
        tfPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfVTCapacity = new javax.swing.JTextField();
        tfSponsor = new javax.swing.JTextField();
        tfPlace = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVenue = new javax.swing.JTable();
        btnRequestVenue = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfeventid = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSponsor = new javax.swing.JTable();
        btnRequestS = new javax.swing.JButton();
        tfS = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEvent = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfn = new javax.swing.JTextField();
        tfid = new javax.swing.JTextField();
        tfvc = new javax.swing.JTextField();
        tfs = new javax.swing.JTextField();
        tfv = new javax.swing.JTextField();
        tfb = new javax.swing.JTextField();
        tfl = new javax.swing.JTextField();
        tfd = new javax.swing.JTextField();
        tfstatus = new javax.swing.JTextField();
        tfcc = new javax.swing.JTextField();
        tftp = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();

        jLabel1.setText("Event name:");

        jLabel2.setText("Date:");

        jLabel3.setText("Place:");

        jLabel4.setText("Sponsor:");

        jLabel5.setText("Customer capacity:");

        jLabel6.setText("Price:");

        jLabel7.setText("Volunteer capacity:");

        tblVenue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "name", "type", "capacity", "zip", "cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVenue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVenueMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVenue);
        if (tblVenue.getColumnModel().getColumnCount() > 0) {
            tblVenue.getColumnModel().getColumn(0).setHeaderValue("id");
            tblVenue.getColumnModel().getColumn(4).setHeaderValue("cost");
        }

        btnRequestVenue.setText("Request venue");
        btnRequestVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestVenueActionPerformed(evt);
            }
        });

        jLabel8.setText("Event ID:");

        tblSponsor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "name", "type", "establish_date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSponsor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSponsorMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSponsor);

        btnRequestS.setText("Request sponsor");
        btnRequestS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestSActionPerformed(evt);
            }
        });

        tfS.setText("How much sponsorship？");
        tfS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSActionPerformed(evt);
            }
        });

        jButton1.setText("Create Event");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfEventName)
                            .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(tfCustomerCapacity)
                            .addComponent(tfPrice)
                            .addComponent(tfVTCapacity)
                            .addComponent(tfSponsor)
                            .addComponent(tfPlace)
                            .addComponent(tfeventid))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRequestVenue)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tfS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRequestS))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jButton1)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(tfeventid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfEventName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfCustomerCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(tfVTCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRequestVenue)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRequestS)
                            .addComponent(tfS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Create event", jPanel2);

        tblEvent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "name", "eventId", "date", "status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEventMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEvent);

        jLabel9.setText("id:");

        jLabel10.setText("name:");

        jLabel11.setText("sponsor:");

        jLabel12.setText("venue:");

        jLabel13.setText("budget:");

        jLabel14.setText("volunteer capacity:");

        jLabel15.setText("date:");

        jLabel16.setText("location:");

        jLabel17.setText("customer capacity:");

        jLabel18.setText("ticket price:");

        jLabel19.setText("status:");

        tfn.setEditable(false);
        tfn.setMinimumSize(new java.awt.Dimension(80, 23));
        tfn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnActionPerformed(evt);
            }
        });

        tfid.setEditable(false);
        tfid.setMinimumSize(new java.awt.Dimension(80, 23));
        tfid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidActionPerformed(evt);
            }
        });

        tfvc.setEditable(false);
        tfvc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfvcActionPerformed(evt);
            }
        });

        tfs.setEditable(false);
        tfs.setMinimumSize(new java.awt.Dimension(80, 23));
        tfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsActionPerformed(evt);
            }
        });

        tfv.setEditable(false);
        tfv.setMinimumSize(new java.awt.Dimension(80, 23));
        tfv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfvActionPerformed(evt);
            }
        });

        tfb.setEditable(false);
        tfb.setMinimumSize(new java.awt.Dimension(80, 23));
        tfb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbActionPerformed(evt);
            }
        });

        tfl.setEditable(false);
        tfl.setMinimumSize(new java.awt.Dimension(80, 23));
        tfl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tflActionPerformed(evt);
            }
        });

        tfd.setEditable(false);
        tfd.setMinimumSize(new java.awt.Dimension(80, 23));
        tfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdActionPerformed(evt);
            }
        });

        tfstatus.setEditable(false);
        tfstatus.setMinimumSize(new java.awt.Dimension(80, 23));
        tfstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfstatusActionPerformed(evt);
            }
        });

        tfcc.setEditable(false);
        tfcc.setMinimumSize(new java.awt.Dimension(80, 23));
        tfcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfccActionPerformed(evt);
            }
        });

        tftp.setEditable(false);
        tftp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftpActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfvc)
                                    .addComponent(tfd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(87, 87, 87)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tftp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(tfstatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(321, 321, 321))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel19))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel16)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfvc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(tfcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(tfn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(tfs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(tfv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tfstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addGap(102, 102, 102))
        );

        jTabbedPane1.addTab("Main", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblVenueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVenueMouseClicked
        int selectedRowIndex = tblVenue.getSelectedRow();
        modelVenue = (DefaultTableModel) tblVenue.getModel();
        selectedVenue = (Venue)modelVenue.getValueAt(tblVenue.convertRowIndexToModel(selectedRowIndex), 0);
        
        
    }//GEN-LAST:event_tblVenueMouseClicked

    private void btnRequestVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestVenueActionPerformed
        String eventid = tfeventid.getText();

        String query = " insert into venue_request(event_id, organiser_id, venue_id, status, amount)"
        + " values ("+eventid+","+ eventOrganizer.getUserAccount().getUser_id()+ "," + selectedVenue.getId()+ "," + "'pending'"+ "," + selectedVenue.getCost()+")";  
        database.insert(query);
        newEvent.setLocation(selectedVenue.getLocation());
        tfPlace.setText(selectedVenue.getLocation()+" request pending");
    }//GEN-LAST:event_btnRequestVenueActionPerformed

    private void tblSponsorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSponsorMouseClicked
       int selectedRowIndex = tblSponsor.getSelectedRow();
        modelS = (DefaultTableModel) tblSponsor.getModel();
        selectedSponsor = (Sponsor)modelS.getValueAt(tblSponsor.convertRowIndexToModel(selectedRowIndex), 0);
        
    }//GEN-LAST:event_tblSponsorMouseClicked

    private void btnRequestSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestSActionPerformed
         int eventid;
        int sponsorship;
        try{
            eventid = Integer.valueOf(tfeventid.getText());
            sponsorship = Integer.valueOf(tfS.getText());
            String query = " insert into sponsor_request(event_id, sponsor_id, status, amount, organizer_id)"
        + " values ("+eventid+","+ selectedSponsor.getLic_no()+ "," + "'pending'"+ ","+ tfS.getText() + "," + eventOrganizer.getUserAccount().getUser_id()+")";  
        database.insert(query);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter number for eventID and sponsorship");
        }
        
        newEvent.setSponsor(selectedSponsor.getName());
        tfSponsor.setText(selectedSponsor.getName()+" request pending");
    }//GEN-LAST:event_btnRequestSActionPerformed

    private void tfSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String eventId = tfeventid.getText();
        String eventName = tfEventName.getText();
        
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        String eventDate = formatter.format(dateChooser.getDate());
        int customerCapacity = Integer.valueOf(tfCustomerCapacity.getText());
        int price = Integer.valueOf(tfPrice.getText());
        String volunteerCapacity = tfVTCapacity.getText();
       
        
        int sponsorship = Integer.valueOf(tfS.getText());
                
        String query = " insert into event(event_id, event_name, budget, status, volunteer_capacity, date, location, event_organizer, customer_capacity, price)"
        + " values ("+eventId+",'"+ eventName+ "'," +sponsorship+","+ "'upcoming'"+ ",'"+volunteerCapacity+"','"+eventDate+"','" +selectedVenue.getLocation()+"',"+ eventOrganizer.getUserAccount().getUser_id()+","+customerCapacity+","+price+")";  
        System.out.println(query);
        database.insert(query);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblEventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEventMouseClicked
        int selectedRowIndex = tblEvent.getSelectedRow();
        modelE = (DefaultTableModel) tblEvent.getModel();
        selectedEvent = (Event)modelE.getValueAt(tblEvent.convertRowIndexToModel(selectedRowIndex), 0);
        tfid.setText(String.valueOf(selectedEvent.getEvent_id()));
        tfn.setText(selectedEvent.getName());
        tfs.setText(selectedEvent.getSponsor());
        tfv.setText(selectedEvent.getVenue());
        tfb.setText(String.valueOf(selectedEvent.getBudget()));
        tfvc.setText(selectedEvent.getVolunteerCapacity());
        tfd.setText(String.valueOf(selectedEvent.getDate()));
        tfl.setText(selectedEvent.getLocation());
        tfcc.setText(selectedEvent.getCustomerCapacity());
        tftp.setText(String.valueOf(selectedEvent.getTicketPrice()));
        tfstatus.setText(selectedEvent.getState());
        
        
        
    }//GEN-LAST:event_tblEventMouseClicked

    private void tfnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnActionPerformed

    private void tfidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfidActionPerformed

    private void tfvcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfvcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfvcActionPerformed

    private void tfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsActionPerformed

    private void tfvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfvActionPerformed

    private void tfbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfbActionPerformed

    private void tflActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tflActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tflActionPerformed

    private void tfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdActionPerformed

    private void tfstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfstatusActionPerformed

    private void tfccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfccActionPerformed

    private void tftpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftpActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       String deletesql = "DELETE FROM event WHERE event_id = " + selectedEvent.getEvent_id()+";";
       database.delete(deletesql);
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRequestS;
    private javax.swing.JButton btnRequestVenue;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblEvent;
    private javax.swing.JTable tblSponsor;
    private javax.swing.JTable tblVenue;
    private javax.swing.JTextField tfCustomerCapacity;
    private javax.swing.JTextField tfEventName;
    private javax.swing.JTextField tfPlace;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfS;
    private javax.swing.JTextField tfSponsor;
    private javax.swing.JTextField tfVTCapacity;
    private javax.swing.JTextField tfb;
    private javax.swing.JTextField tfcc;
    private javax.swing.JTextField tfd;
    private javax.swing.JTextField tfeventid;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tfl;
    private javax.swing.JTextField tfn;
    private javax.swing.JTextField tfs;
    private javax.swing.JTextField tfstatus;
    private javax.swing.JTextField tftp;
    private javax.swing.JTextField tfv;
    private javax.swing.JTextField tfvc;
    // End of variables declaration//GEN-END:variables


    public void dbGetVenue(){
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/ems_5100","root","root");   
            Statement stmt=con.createStatement();  
            ResultSet rs=stmt.executeQuery("select * from venue");  
            
            while(rs.next()) {
                Venue venue = new Venue();
                venue.setId(rs.getInt("reg_id"));
                venue.setName(rs.getString("name"));
                venue.setType(rs.getString("type"));
                venue.setCapacity(rs.getInt("seat_capacity"));
                venue.setLocation(rs.getString("zip_code"));
                venue.setCost(rs.getInt("cost"));
                venues.add(venue);
            }

            rs.close();
            con.close();  
            }catch(Exception e){ System.out.println(e);}  
    }
    
    
    public void populateVenueTable() {
        modelVenue = (DefaultTableModel) tblVenue.getModel();
        modelVenue.setRowCount(0);
        for(Venue venue: venues) {
            Object[] row = new Object[5];
            row[0] = venue;
            row[1] = venue.getType();
            row[2] = venue.getCapacity();
            row[3] = venue.getLocation();
            row[4] = venue.getCost();
            modelVenue.addRow(row);
        }
    }

    private void dbGetSponsor() {
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/ems_5100","root","root");   
            Statement stmt=con.createStatement();  
            ResultSet rs=stmt.executeQuery("select * from sponsor");  
            
            while(rs.next()) {
                Sponsor sponsor = new Sponsor();
                sponsor.setLic_no(rs.getInt("reg_id"));
                sponsor.setBusiness_type(rs.getString("type"));
                sponsor.setEst_date(rs.getDate("establish_date"));
                sponsor.setName(rs.getString("name"));
                
                sponsors.add(sponsor);
            }
            rs.close();
            con.close();  
            }catch(Exception e){ System.out.println(e);}  
        
    }

    private void populateSponsorTable() {
        modelS= (DefaultTableModel) tblSponsor.getModel();
        modelS.setRowCount(0);
        for(Sponsor sponsor: sponsors) {
            Object[] row = new Object[3];
            row[0] = sponsor;
            row[1] = sponsor.getBusiness_type();
            row[2] = sponsor.getEst_date(); 
            modelS.addRow(row);
        }
    }
    
    
    private void dbGetEvent() {
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/ems_5100","root","root");   
            Statement stmt=con.createStatement();  
            ResultSet rs=stmt.executeQuery("select * from event WHERE event_organizer ='"+ eventOrganizer.getUserAccount().getUser_id()+"';");  
            System.out.println("select * from event WHERE event_organizer ='"+ eventOrganizer.getUserAccount().getUser_id()+"';");
          
            
            while(rs.next()) {
                Event event = new Event();
                event.setEvent_id(rs.getInt("event_id"));
                event.setName(rs.getString("event_name"));
                event.setDate(rs.getDate("date"));
                event.setState(rs.getString("status"));
                event.setSponsor(rs.getString("sponsor_id"));
                event.setVenue(rs.getString("venue_id"));
                event.setBudget(rs.getInt("budget"));
                event.setVolunteerCapacity("volunteer_capacity");
                event.setLocation(rs.getString("location"));
                event.setEventOrganizer(rs.getString("event_organizer"));
                event.setCustomerCapacity(rs.getString("customer_capacity"));
                event.setTicketPrice(rs.getInt("price"));
                events.add(event);
            }
            rs.close();
            con.close();  
            }catch(Exception e){ System.out.println(e);}  
        
    }
    
    private void populateEventTable() {
        modelE = (DefaultTableModel) tblEvent.getModel();
        modelE.setRowCount(0);
        for(Event event: events) {
            Object[] row = new Object[4];
            row[0] = event;
            row[1] = event.getEvent_id();
            row[2] = event.getDate();
            row[3] = event.getState();
            modelE.addRow(row);
        }
    }
    
    
    

}
