/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Sponsor;

import javax.swing.JPanel;

/**
 *
 * @author evelynzu
 */
public class SponsorMain extends javax.swing.JPanel {

    /**
     * Creates new form SponsorMain
     */
    javax.swing.JPanel CardSequencePanel;
    public SponsorMain(JPanel clp) {
        this.CardSequencePanel = clp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblsponsorname = new javax.swing.JLabel();
        btnbzcheckrequest = new javax.swing.JButton();
        lblbztype = new javax.swing.JLabel();
        lblbzdate = new javax.swing.JLabel();
        txtbztype = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        jLabel1.setText("Welcome, Sponsor");

        lblsponsorname.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblsponsorname.setText("<Sponsor Business>");

        btnbzcheckrequest.setText("Check Request");
        btnbzcheckrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbzcheckrequestActionPerformed(evt);
            }
        });

        lblbztype.setText("Business Type:");

        lblbzdate.setText("Date Established:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lblsponsorname)
                        .addGap(196, 196, 196)
                        .addComponent(btnbzcheckrequest))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblbzdate)
                            .addComponent(lblbztype))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtbztype)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblsponsorname)
                            .addComponent(btnbzcheckrequest))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblbztype)
                            .addComponent(txtbztype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblbzdate)))
                .addContainerGap(321, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbzcheckrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbzcheckrequestActionPerformed
        SponsorRequestList sponsorRequestList = new SponsorRequestList(CardSequencePanel);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("Request list", sponsorRequestList);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnbzcheckrequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbzcheckrequest;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblbzdate;
    private javax.swing.JLabel lblbztype;
    private javax.swing.JLabel lblsponsorname;
    private javax.swing.JTextField txtbztype;
    // End of variables declaration//GEN-END:variables
}
